# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "Build and test"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ cpp ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update
        run: sudo apt update -y

      - name: Installs
        run: sudo apt install -y libcmocka-dev

      - name: Configure
        run: ./autogen.sh --enable-test

      - name: Build
        run: make -j

      - name: Test environment setup
        run: sudo modprobe -a vcan && sudo modprobe -a vxcan

      - name: Test
        run: sudo ./test/run-test.sh

      - name: Check Test Coverage
        uses: threeal/gcovr-action@v1.1.0
        with:
          coveralls-send: true
